apiVersion: v1
kind: Secret
metadata:
  name: news-platform-secrets
  namespace: news-platform
type: Opaque
stringData:
  MINIO_SECRET_KEY: "minioadmin123"
  POSTGRES_PASSWORD: "newsadmin123"
  AIRFLOW_ADMIN_PASSWORD: "admin123"
  GRAFANA_ADMIN_PASSWORD: "admin123"
